import { applicantStageLabel, type ApplicantInterviewMode } from "@/lib/applicant-stage-labels";
import { applyEmailExtras, emailSignoff, renderEventEmail, type EmailOverride, type EmailPlaceholder } from "@/lib/email-templates";
import { pilotOutboundEmailEnabled } from "@/lib/pilot-email-policy";

/**
 * Human-readable copy for the recruitment notification queue. The stored
 * `notificationEventType` and workflow stage keys are canonical values; these
 * helpers turn them into the wording used in HR and candidate emails so the
 * n8n notifier never has to render raw keys such as `voice_result_next_step`.
 */
const EVENT_LABELS: Record<string, string> = {
  application_acknowledgment: "Application received",
  application_stage_update: "Application status update",
  screening_next_step: "CV screening completed",
  voice_booking_invitation: "Voice interview invitation",
  voice_booking_confirmation: "Voice interview scheduled",
  voice_result_next_step: "Voice interview complete — review required",
  voice_no_show: "Voice interview missed — action required",
  voice_retry: "Voice interview retry scheduled",
  voice_rejection: "Voice interview — candidate not shortlisted",
  final_booking_invitation: "Face-to-face interview invitation",
  final_booking_confirmation: "Face-to-face interview scheduled",
  final_decision_pass: "Face-to-face interview — candidate passed",
  final_decision_reject: "Face-to-face interview — candidate not selected",
};

const EVENT_SUMMARIES: Record<string, string> = {
  application_acknowledgment: "The candidate's application has been received and is now in the review queue.",
  screening_next_step: "CV screening is complete. Review the recommendation and decide whether to move the candidate forward.",
  voice_booking_invitation: "A booking invitation is ready for the candidate. No call will be placed until the candidate selects a time.",
  voice_booking_confirmation: "The candidate has selected a time for the AI voice interview. Review the booking details below and the applicant record before the call.",
  voice_result_next_step: "The AI voice interview is complete. Review the transcript and evaluation, then record the next-step decision.",
  voice_no_show: "The candidate did not attend the scheduled AI voice interview. Review the record and decide whether to send a new invitation.",
  voice_retry: "The AI voice interview call did not connect. A new attempt has been scheduled automatically.",
  voice_rejection: "The candidate was not shortlisted after the AI voice interview.",
  final_booking_invitation: "A booking invitation is ready for the candidate's face-to-face interview.",
  final_booking_confirmation: "The candidate has selected a time for the face-to-face interview.",
  final_decision_pass: "The candidate passed the face-to-face interview.",
  final_decision_reject: "The candidate was not selected after the face-to-face interview.",
};

function normalize(value: string | null | undefined) {
  return String(value || "").trim().toLowerCase();
}

function titleCase(value: string) {
  return value.replace(/_/g, " ").replace(/\b\w/g, (character) => character.toUpperCase());
}

/** Email-ready name for a notification event, e.g. "Voice interview complete — review required". */
export function notificationEventLabel(eventType: string | null | undefined) {
  const key = normalize(eventType);
  return EVENT_LABELS[key] || (key ? titleCase(key) : "Recruitment update");
}

/** Email-ready stage wording follows the interview route on that application. */
export function notificationStatusLabel(stage: string | null | undefined, mode: ApplicantInterviewMode) {
  return applicantStageLabel(stage, mode) || "";
}

/** A sentence describing the update. Falls back to the reviewer's comment, then a generic line. */
export function notificationSummary(eventType: string | null | undefined, comments?: string | null) {
  const trimmed = String(comments || "").trim();
  if (trimmed) return trimmed;
  return EVENT_SUMMARIES[normalize(eventType)] || "A recruitment workflow update requires your attention.";
}


const AI_INTERVIEW_NOTICE = "AI Interview Notice: This interview will be conducted with the assistance of an AI interviewing system, which may record, transcribe and assess your responses against job-related criteria. Any information or responses generated by the AI should not be considered an official representation, commitment or offer by McLink Group unless confirmed in writing by an authorized representative.";

const EMAIL_SUBJECTS: Record<string, string> = {
  voice_booking_invitation: "Schedule your AI voice interview | McLink Group",
  voice_booking_confirmation: "Your AI voice interview is confirmed | McLink Group",
  final_booking_invitation: "Schedule Your Final Interview with McLink Group",
  voice_result_next_step: "Your McLink Group application — next steps",
  voice_no_show: "Your missed AI voice interview with McLink Group",
  voice_retry: "We will call you again for your AI voice interview",
  voice_rejection: "Update on your McLink Group application",
  screening_next_step: "Your McLink Group application has been reviewed",
  application_acknowledgment: "We have received your McLink Group application",
};

export type NotificationEmailContext = {
  /** The organization's display name, used in subjects, bodies and the sign-off. */
  companyName?: string | null;
  /** The organization's edited subject and body for this event, when it has made one. */
  template?: EmailOverride | null;
  candidateName?: string | null;
  roleTitle?: string | null;
  bookingLink?: string | null;
  avatarLink?: string | null;
  /** Human date/time already formatted with its timezone, for confirmations. */
  scheduledLabel?: string | null;
  /** The interview the candidate took ("avatar" or "voice"), so follow-up emails name the right one. */
  interviewMode?: string | null;
};

export type NotificationEmailCopy = {
  subject: string;
  heading: string;
  message: string;
  cta: string;
  ctaLink: string;
  /** n8n should render the CTA as a button and never append this URL as text. */
  includeRawBookingLink: false;
  secondaryCta: string;
  secondaryCtaLink: string;
  signoff: string;
  /** Optional header image (a public https link), or "" for none. The senders show it above the text. */
  imageUrl: string;
  imageAlt: string;
};

type EmailCopyBody = Omit<NotificationEmailCopy, "imageUrl" | "imageAlt">;

/**
 * Candidate-facing email copy for a notification event. The n8n notifier
 * renders these fields directly so wording lives with the workflow, not in a
 * separate template. Returns `null` for events that must not send an email
 * (e.g. the face-to-face booking confirmation, which Google Calendar covers).
 */
function buildNotificationEmail(eventType: string | null | undefined, context: NotificationEmailContext): EmailCopyBody | null {
  if (!pilotOutboundEmailEnabled()) return null;

  const key = normalize(eventType);
  if (key === "final_booking_confirmation") return null;

  const name = String(context.candidateName || "").trim() || "there";
  const role = String(context.roleTitle || "").trim();
  const rolePhrase = role ? `the ${role} position` : "this position";
  const link = String(context.bookingLink || "").trim();
  const avatarLink = String(context.avatarLink || "").trim();
  const scheduled = String(context.scheduledLabel || "").trim();
  const companyName = String(context.companyName || "").trim() || "McLink Group";

  const templateValues: Partial<Record<EmailPlaceholder, string>> = {
    candidate_name: name,
    role_title: role,
    role_phrase: rolePhrase,
    company_name: companyName,
    interview_time: scheduled,
    interview_type: context.interviewMode === "avatar" ? "Live Avatar interview" : context.interviewMode === "voice" ? "AI voice interview" : "interview",
  };

  const base = { subject: EMAIL_SUBJECTS[key] || notificationEventLabel(key), signoff: emailSignoff(companyName), cta: "", ctaLink: "", secondaryCta: "", secondaryCtaLink: "", includeRawBookingLink: false as const };

  switch (key) {
    case "voice_booking_invitation": {
      // HR sent only a Live Avatar interview (no call option): its own,
      // editable wording ("avatar_interview_invitation") with the avatar link
      // as the one action. The queue passes that event's saved template.
      if (!link && avatarLink) {
        const avatar = renderEventEmail("avatar_interview_invitation", templateValues, context.template);
        return { ...base, subject: avatar.subject, signoff: emailSignoff(companyName), heading: "Your Live Avatar interview", message: avatar.body, cta: "Start your Live Avatar interview", ctaLink: avatarLink, secondaryCta: "", secondaryCtaLink: "" };
      }
      const { subject, body } = renderEventEmail(key, templateValues, context.template);
      return {
        ...base,
        subject,
        signoff: emailSignoff(companyName),
        heading: "Schedule your AI voice interview",
        message: body,
        cta: "Schedule a call",
        ctaLink: link,
        secondaryCta: avatarLink ? "Interview with our Avatar now" : "",
        secondaryCtaLink: avatarLink,
      };
    }
    case "voice_booking_confirmation": {
      const { subject, body } = renderEventEmail(key, templateValues, context.template);
      return { ...base, subject, signoff: emailSignoff(companyName), heading: "Your AI voice interview is confirmed", message: body, cta: "", ctaLink: "" };
    }
    case "final_booking_invitation": {
      const { subject, body } = renderEventEmail(key, templateValues, context.template);
      return { ...base, subject, signoff: emailSignoff(companyName), heading: "Schedule Your Final Interview", message: body, cta: "Schedule Final Interview", ctaLink: link };
    }
    // The event summaries above are written for HR reviewers, so events that are
    // emailed to the candidate need their own candidate-facing wording.
    case "application_acknowledgment":
      return {
        ...base,
        heading: "Application received",
        message: `Dear ${name},\n\nThank you for applying for ${rolePhrase} at McLink Group. We have received your application and our recruitment team will review it. We will be in touch if we would like to take the next step.`,
      };
    case "screening_next_step":
      return {
        ...base,
        heading: "Your application is being reviewed",
        message: `Dear ${name},\n\nThank you for your interest in ${rolePhrase}. Your application has been assessed and is now with our recruitment team for review. We will contact you about the next steps.`,
      };
    case "voice_result_next_step":
      return {
        ...base,
        heading: "Thank you for completing your interview",
        message: `Dear ${name},\n\nThank you for completing your AI voice interview for ${rolePhrase}. Our recruitment team is now reviewing your interview and will contact you about the next steps.`,
      };
    case "voice_no_show":
      return {
        ...base,
        heading: "We could not complete your interview",
        message: `Dear ${name},\n\nWe were unable to complete your scheduled AI voice interview for ${rolePhrase}. Our recruitment team will be in touch about whether a new time can be arranged.`,
      };
    case "voice_retry":
      return {
        ...base,
        heading: "We will call you again",
        message: `Dear ${name},\n\nWe tried to call you for your AI voice interview for ${rolePhrase} but could not connect. We will try again shortly, so please keep your phone available.`,
      };
    case "voice_rejection":
      return {
        ...base,
        heading: "Update on your application",
        message: `Dear ${name},\n\nThank you for taking the time to interview for ${rolePhrase}. After careful consideration we will not be moving forward with your application at this time. We appreciate your interest in McLink Group and wish you every success.`,
      };
    // Internal outcome notes for HR; the candidate hears about these through a
    // separate, deliberate follow-up, not an automatic email.
    case "final_decision_pass":
    case "final_decision_reject":
      return null;
    default:
      return {
        ...base,
        heading: notificationEventLabel(key),
        message: `Dear ${name},\n\n${notificationSummary(key)}`,
        cta: link ? "Open secure link" : "",
        ctaLink: link,
      };
  }
}

export type RoleNotificationEmailContext = {
  companyName?: string | null;
  template?: EmailOverride | null;
  recipientName?: string | null;
  roleTitle?: string | null;
  roleExternalId?: string | null;
  departmentSnapshot?: string | null;
  requesterName?: string | null;
  requesterEmail?: string | null;
  roleLink?: string | null;
};

/**
 * Internal-staff-facing email copy for a role-domain notification (recipient
 * is the org's first registered account, not a candidate). Only job_posted is
 * ever queued for email today (see notificationQueue's role-side allowlist),
 * but this stays keyed by status so a future role event can add a case here
 * without touching the sender.
 */
function buildRoleNotificationEmail(newStatus: string | null | undefined, context: RoleNotificationEmailContext): EmailCopyBody | null {
  if (!pilotOutboundEmailEnabled()) return null;
  const key = normalize(newStatus);
  if (key !== "job_posted") return null;

  const recipientName = String(context.recipientName || "").trim() || "there";
  const roleTitle = String(context.roleTitle || "").trim() || "A role";
  const roleExternalId = String(context.roleExternalId || "").trim();
  const department = String(context.departmentSnapshot || "").trim();
  const requester = String(context.requesterName || "").trim() || String(context.requesterEmail || "").trim();
  const link = String(context.roleLink || "").trim();

  const { subject, body } = renderEventEmail("job_posted", {
    recipient_name: recipientName,
    role_title: roleTitle,
    role_id: roleExternalId ? `(${roleExternalId})` : "",
    department: department ? `in ${department}` : "",
    requested_by: requester,
    company_name: String(context.companyName || "").trim() || "McLink Group",
  }, context.template);
  return {
    subject,
    heading: "New role posted",
    message: body,
    cta: link ? "View role" : "",
    ctaLink: link,
    secondaryCta: "",
    secondaryCtaLink: "",
    includeRawBookingLink: false,
    signoff: emailSignoff(String(context.companyName || "").trim() || "McLink Group"),
  };
}

/** Candidate-facing copy for an event, with the organization's button labels and header image applied. */
export function notificationEmail(eventType: string | null | undefined, context: NotificationEmailContext = {}): NotificationEmailCopy | null {
  const copy = buildNotificationEmail(eventType, context);
  return copy ? applyEmailExtras(copy, context.template) : null;
}

/** Staff-facing copy for a role event, with the organization's button label and header image applied. */
export function roleNotificationEmail(newStatus: string | null | undefined, context: RoleNotificationEmailContext = {}): NotificationEmailCopy | null {
  const copy = buildRoleNotificationEmail(newStatus, context);
  return copy ? applyEmailExtras(copy, context.template) : null;
}
